CREATE DATABASE IF NOT EXISTS farmer_portal;
USE farmer_portal;

CREATE TABLE IF NOT EXISTS farmers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    aadhaar VARCHAR(12) NOT NULL UNIQUE,
    mobile VARCHAR(10) NOT NULL,
    state VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
